---
igwn_conda_root: "/cvmfs/oasis.opensciencegrid.org/ligo/sw/conda"
igwn_env_name:
  - igwn-py36
  - igwn-py36-proposed
  - igwn-py36-testing
  - igwn-py37
  - igwn-py37-proposed
  - igwn-py37-testing
  - igwn-py38
  - igwn-py38-proposed
  - igwn-py38-testing
jupyter_server_user: jupyterhub
jupyter_server_sudo_group: LIGO
jupyterhub_config_directory: "/etc/jupyterhub"
jupyterhub_log_directory: "/var/log/jupyterhub"
jupyterhub_datadir: "/usr/local/share/jupyter"
jupyterhub_prefix: "/opt/jupyterhub"
...
